//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace klient_wpf.Glowny {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Uzytkownik", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Uzytkownik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long identyfikatorUzytkownikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwaUzytkownikaField;
        
        private long numerPokojuField;
        
        private long kasioraField;
        
        private bool foldField;
        
        private bool startField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long identyfikatorUzytkownika {
            get {
                return this.identyfikatorUzytkownikaField;
            }
            set {
                if ((this.identyfikatorUzytkownikaField.Equals(value) != true)) {
                    this.identyfikatorUzytkownikaField = value;
                    this.RaisePropertyChanged("identyfikatorUzytkownika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nazwaUzytkownika {
            get {
                return this.nazwaUzytkownikaField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwaUzytkownikaField, value) != true)) {
                    this.nazwaUzytkownikaField = value;
                    this.RaisePropertyChanged("nazwaUzytkownika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                if ((this.numerPokojuField.Equals(value) != true)) {
                    this.numerPokojuField = value;
                    this.RaisePropertyChanged("numerPokoju");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long kasiora {
            get {
                return this.kasioraField;
            }
            set {
                if ((this.kasioraField.Equals(value) != true)) {
                    this.kasioraField = value;
                    this.RaisePropertyChanged("kasiora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool fold {
            get {
                return this.foldField;
            }
            set {
                if ((this.foldField.Equals(value) != true)) {
                    this.foldField = value;
                    this.RaisePropertyChanged("fold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Komunikat", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Komunikat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trescKomunikatuField;
        
        private long kodKomunikatuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string trescKomunikatu {
            get {
                return this.trescKomunikatuField;
            }
            set {
                if ((object.ReferenceEquals(this.trescKomunikatuField, value) != true)) {
                    this.trescKomunikatuField = value;
                    this.RaisePropertyChanged("trescKomunikatu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long kodKomunikatu {
            get {
                return this.kodKomunikatuField;
            }
            set {
                if ((this.kodKomunikatuField.Equals(value) != true)) {
                    this.kodKomunikatuField = value;
                    this.RaisePropertyChanged("kodKomunikatu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wiadomosc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Wiadomosc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwaUzytkownikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trescWiadomosciField;
        
        private int stempelCzasowyField;
        
        private long numerPokojuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nazwaUzytkownika {
            get {
                return this.nazwaUzytkownikaField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwaUzytkownikaField, value) != true)) {
                    this.nazwaUzytkownikaField = value;
                    this.RaisePropertyChanged("nazwaUzytkownika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string trescWiadomosci {
            get {
                return this.trescWiadomosciField;
            }
            set {
                if ((object.ReferenceEquals(this.trescWiadomosciField, value) != true)) {
                    this.trescWiadomosciField = value;
                    this.RaisePropertyChanged("trescWiadomosci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int stempelCzasowy {
            get {
                return this.stempelCzasowyField;
            }
            set {
                if ((this.stempelCzasowyField.Equals(value) != true)) {
                    this.stempelCzasowyField = value;
                    this.RaisePropertyChanged("stempelCzasowy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long numerPokoju {
            get {
                return this.numerPokojuField;
            }
            set {
                if ((this.numerPokojuField.Equals(value) != true)) {
                    this.numerPokojuField = value;
                    this.RaisePropertyChanged("numerPokoju");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Glowny.GlownySoap")]
    public interface GlownySoap {
        
        // CODEGEN: Generating message contract since element name ZwrocZalogowanychResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZwrocZalogowanych", ReplyAction="*")]
        klient_wpf.Glowny.ZwrocZalogowanychResponse ZwrocZalogowanych(klient_wpf.Glowny.ZwrocZalogowanychRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZwrocZalogowanych", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.ZwrocZalogowanychResponse> ZwrocZalogowanychAsync(klient_wpf.Glowny.ZwrocZalogowanychRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dodajZw", ReplyAction="*")]
        bool dodajZw();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dodajZw", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> dodajZwAsync();
        
        // CODEGEN: Generating message contract since element name nazwa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Zarejestruj", ReplyAction="*")]
        klient_wpf.Glowny.ZarejestrujResponse Zarejestruj(klient_wpf.Glowny.ZarejestrujRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Zarejestruj", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.ZarejestrujResponse> ZarejestrujAsync(klient_wpf.Glowny.ZarejestrujRequest request);
        
        // CODEGEN: Generating message contract since element name nazwa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprawdzNazwe", ReplyAction="*")]
        klient_wpf.Glowny.SprawdzNazweResponse SprawdzNazwe(klient_wpf.Glowny.SprawdzNazweRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprawdzNazwe", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.SprawdzNazweResponse> SprawdzNazweAsync(klient_wpf.Glowny.SprawdzNazweRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprawdzEmail", ReplyAction="*")]
        klient_wpf.Glowny.SprawdzEmailResponse SprawdzEmail(klient_wpf.Glowny.SprawdzEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprawdzEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.SprawdzEmailResponse> SprawdzEmailAsync(klient_wpf.Glowny.SprawdzEmailRequest request);
        
        // CODEGEN: Generating message contract since element name nazwa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Zaloguj", ReplyAction="*")]
        klient_wpf.Glowny.ZalogujResponse Zaloguj(klient_wpf.Glowny.ZalogujRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Zaloguj", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.ZalogujResponse> ZalogujAsync(klient_wpf.Glowny.ZalogujRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Wyloguj", ReplyAction="*")]
        klient_wpf.Glowny.WylogujResponse Wyloguj(klient_wpf.Glowny.WylogujRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Wyloguj", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.WylogujResponse> WylogujAsync(klient_wpf.Glowny.WylogujRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzSwojeID", ReplyAction="*")]
        klient_wpf.Glowny.PobierzSwojeIDResponse PobierzSwojeID(klient_wpf.Glowny.PobierzSwojeIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzSwojeID", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.PobierzSwojeIDResponse> PobierzSwojeIDAsync(klient_wpf.Glowny.PobierzSwojeIDRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzUzytkownikow", ReplyAction="*")]
        klient_wpf.Glowny.PobierzUzytkownikowResponse PobierzUzytkownikow(klient_wpf.Glowny.PobierzUzytkownikowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzUzytkownikow", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.PobierzUzytkownikowResponse> PobierzUzytkownikowAsync(klient_wpf.Glowny.PobierzUzytkownikowRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzWiadomosci", ReplyAction="*")]
        klient_wpf.Glowny.PobierzWiadomosciResponse PobierzWiadomosci(klient_wpf.Glowny.PobierzWiadomosciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzWiadomosci", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.PobierzWiadomosciResponse> PobierzWiadomosciAsync(klient_wpf.Glowny.PobierzWiadomosciRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WyslijWiadomosc", ReplyAction="*")]
        klient_wpf.Glowny.WyslijWiadomoscResponse WyslijWiadomosc(klient_wpf.Glowny.WyslijWiadomoscRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WyslijWiadomosc", ReplyAction="*")]
        System.Threading.Tasks.Task<klient_wpf.Glowny.WyslijWiadomoscResponse> WyslijWiadomoscAsync(klient_wpf.Glowny.WyslijWiadomoscRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZwrocZalogowanychRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZwrocZalogowanych", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.ZwrocZalogowanychRequestBody Body;
        
        public ZwrocZalogowanychRequest() {
        }
        
        public ZwrocZalogowanychRequest(klient_wpf.Glowny.ZwrocZalogowanychRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ZwrocZalogowanychRequestBody {
        
        public ZwrocZalogowanychRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZwrocZalogowanychResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZwrocZalogowanychResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.ZwrocZalogowanychResponseBody Body;
        
        public ZwrocZalogowanychResponse() {
        }
        
        public ZwrocZalogowanychResponse(klient_wpf.Glowny.ZwrocZalogowanychResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZwrocZalogowanychResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public klient_wpf.Glowny.Uzytkownik[] ZwrocZalogowanychResult;
        
        public ZwrocZalogowanychResponseBody() {
        }
        
        public ZwrocZalogowanychResponseBody(klient_wpf.Glowny.Uzytkownik[] ZwrocZalogowanychResult) {
            this.ZwrocZalogowanychResult = ZwrocZalogowanychResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZarejestrujRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Zarejestruj", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.ZarejestrujRequestBody Body;
        
        public ZarejestrujRequest() {
        }
        
        public ZarejestrujRequest(klient_wpf.Glowny.ZarejestrujRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZarejestrujRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nazwa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string haslo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        public ZarejestrujRequestBody() {
        }
        
        public ZarejestrujRequestBody(string nazwa, string haslo, string email) {
            this.nazwa = nazwa;
            this.haslo = haslo;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZarejestrujResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZarejestrujResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.ZarejestrujResponseBody Body;
        
        public ZarejestrujResponse() {
        }
        
        public ZarejestrujResponse(klient_wpf.Glowny.ZarejestrujResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZarejestrujResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public klient_wpf.Glowny.Komunikat ZarejestrujResult;
        
        public ZarejestrujResponseBody() {
        }
        
        public ZarejestrujResponseBody(klient_wpf.Glowny.Komunikat ZarejestrujResult) {
            this.ZarejestrujResult = ZarejestrujResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzNazweRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SprawdzNazwe", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.SprawdzNazweRequestBody Body;
        
        public SprawdzNazweRequest() {
        }
        
        public SprawdzNazweRequest(klient_wpf.Glowny.SprawdzNazweRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SprawdzNazweRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nazwa;
        
        public SprawdzNazweRequestBody() {
        }
        
        public SprawdzNazweRequestBody(string nazwa) {
            this.nazwa = nazwa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzNazweResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SprawdzNazweResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.SprawdzNazweResponseBody Body;
        
        public SprawdzNazweResponse() {
        }
        
        public SprawdzNazweResponse(klient_wpf.Glowny.SprawdzNazweResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SprawdzNazweResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public klient_wpf.Glowny.Komunikat SprawdzNazweResult;
        
        public SprawdzNazweResponseBody() {
        }
        
        public SprawdzNazweResponseBody(klient_wpf.Glowny.Komunikat SprawdzNazweResult) {
            this.SprawdzNazweResult = SprawdzNazweResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SprawdzEmail", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.SprawdzEmailRequestBody Body;
        
        public SprawdzEmailRequest() {
        }
        
        public SprawdzEmailRequest(klient_wpf.Glowny.SprawdzEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SprawdzEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public SprawdzEmailRequestBody() {
        }
        
        public SprawdzEmailRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SprawdzEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.SprawdzEmailResponseBody Body;
        
        public SprawdzEmailResponse() {
        }
        
        public SprawdzEmailResponse(klient_wpf.Glowny.SprawdzEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SprawdzEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public klient_wpf.Glowny.Komunikat SprawdzEmailResult;
        
        public SprawdzEmailResponseBody() {
        }
        
        public SprawdzEmailResponseBody(klient_wpf.Glowny.Komunikat SprawdzEmailResult) {
            this.SprawdzEmailResult = SprawdzEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZalogujRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Zaloguj", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.ZalogujRequestBody Body;
        
        public ZalogujRequest() {
        }
        
        public ZalogujRequest(klient_wpf.Glowny.ZalogujRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZalogujRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nazwa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string haslo;
        
        public ZalogujRequestBody() {
        }
        
        public ZalogujRequestBody(string nazwa, string haslo) {
            this.nazwa = nazwa;
            this.haslo = haslo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZalogujResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZalogujResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.ZalogujResponseBody Body;
        
        public ZalogujResponse() {
        }
        
        public ZalogujResponse(klient_wpf.Glowny.ZalogujResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZalogujResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ZalogujResult;
        
        public ZalogujResponseBody() {
        }
        
        public ZalogujResponseBody(byte[] ZalogujResult) {
            this.ZalogujResult = ZalogujResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WylogujRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Wyloguj", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.WylogujRequestBody Body;
        
        public WylogujRequest() {
        }
        
        public WylogujRequest(klient_wpf.Glowny.WylogujRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WylogujRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] token;
        
        public WylogujRequestBody() {
        }
        
        public WylogujRequestBody(byte[] token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WylogujResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WylogujResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.WylogujResponseBody Body;
        
        public WylogujResponse() {
        }
        
        public WylogujResponse(klient_wpf.Glowny.WylogujResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WylogujResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public klient_wpf.Glowny.Komunikat WylogujResult;
        
        public WylogujResponseBody() {
        }
        
        public WylogujResponseBody(klient_wpf.Glowny.Komunikat WylogujResult) {
            this.WylogujResult = WylogujResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzSwojeIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzSwojeID", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.PobierzSwojeIDRequestBody Body;
        
        public PobierzSwojeIDRequest() {
        }
        
        public PobierzSwojeIDRequest(klient_wpf.Glowny.PobierzSwojeIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzSwojeIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] token;
        
        public PobierzSwojeIDRequestBody() {
        }
        
        public PobierzSwojeIDRequestBody(byte[] token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzSwojeIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzSwojeIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.PobierzSwojeIDResponseBody Body;
        
        public PobierzSwojeIDResponse() {
        }
        
        public PobierzSwojeIDResponse(klient_wpf.Glowny.PobierzSwojeIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzSwojeIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public klient_wpf.Glowny.Komunikat PobierzSwojeIDResult;
        
        public PobierzSwojeIDResponseBody() {
        }
        
        public PobierzSwojeIDResponseBody(klient_wpf.Glowny.Komunikat PobierzSwojeIDResult) {
            this.PobierzSwojeIDResult = PobierzSwojeIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzUzytkownikowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzUzytkownikow", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.PobierzUzytkownikowRequestBody Body;
        
        public PobierzUzytkownikowRequest() {
        }
        
        public PobierzUzytkownikowRequest(klient_wpf.Glowny.PobierzUzytkownikowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzUzytkownikowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] token;
        
        public PobierzUzytkownikowRequestBody() {
        }
        
        public PobierzUzytkownikowRequestBody(byte[] token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzUzytkownikowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzUzytkownikowResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.PobierzUzytkownikowResponseBody Body;
        
        public PobierzUzytkownikowResponse() {
        }
        
        public PobierzUzytkownikowResponse(klient_wpf.Glowny.PobierzUzytkownikowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzUzytkownikowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public klient_wpf.Glowny.Uzytkownik[] PobierzUzytkownikowResult;
        
        public PobierzUzytkownikowResponseBody() {
        }
        
        public PobierzUzytkownikowResponseBody(klient_wpf.Glowny.Uzytkownik[] PobierzUzytkownikowResult) {
            this.PobierzUzytkownikowResult = PobierzUzytkownikowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzWiadomosciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzWiadomosci", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.PobierzWiadomosciRequestBody Body;
        
        public PobierzWiadomosciRequest() {
        }
        
        public PobierzWiadomosciRequest(klient_wpf.Glowny.PobierzWiadomosciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzWiadomosciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int timT;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long pokoj;
        
        public PobierzWiadomosciRequestBody() {
        }
        
        public PobierzWiadomosciRequestBody(byte[] token, int timT, long pokoj) {
            this.token = token;
            this.timT = timT;
            this.pokoj = pokoj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzWiadomosciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzWiadomosciResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.PobierzWiadomosciResponseBody Body;
        
        public PobierzWiadomosciResponse() {
        }
        
        public PobierzWiadomosciResponse(klient_wpf.Glowny.PobierzWiadomosciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzWiadomosciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public klient_wpf.Glowny.Wiadomosc[] PobierzWiadomosciResult;
        
        public PobierzWiadomosciResponseBody() {
        }
        
        public PobierzWiadomosciResponseBody(klient_wpf.Glowny.Wiadomosc[] PobierzWiadomosciResult) {
            this.PobierzWiadomosciResult = PobierzWiadomosciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WyslijWiadomoscRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WyslijWiadomosc", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.WyslijWiadomoscRequestBody Body;
        
        public WyslijWiadomoscRequest() {
        }
        
        public WyslijWiadomoscRequest(klient_wpf.Glowny.WyslijWiadomoscRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WyslijWiadomoscRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public klient_wpf.Glowny.Wiadomosc wiadomosc;
        
        public WyslijWiadomoscRequestBody() {
        }
        
        public WyslijWiadomoscRequestBody(byte[] token, klient_wpf.Glowny.Wiadomosc wiadomosc) {
            this.token = token;
            this.wiadomosc = wiadomosc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WyslijWiadomoscResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WyslijWiadomoscResponse", Namespace="http://tempuri.org/", Order=0)]
        public klient_wpf.Glowny.WyslijWiadomoscResponseBody Body;
        
        public WyslijWiadomoscResponse() {
        }
        
        public WyslijWiadomoscResponse(klient_wpf.Glowny.WyslijWiadomoscResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WyslijWiadomoscResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public klient_wpf.Glowny.Komunikat WyslijWiadomoscResult;
        
        public WyslijWiadomoscResponseBody() {
        }
        
        public WyslijWiadomoscResponseBody(klient_wpf.Glowny.Komunikat WyslijWiadomoscResult) {
            this.WyslijWiadomoscResult = WyslijWiadomoscResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlownySoapChannel : klient_wpf.Glowny.GlownySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlownySoapClient : System.ServiceModel.ClientBase<klient_wpf.Glowny.GlownySoap>, klient_wpf.Glowny.GlownySoap {
        
        public GlownySoapClient() {
        }
        
        public GlownySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlownySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlownySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlownySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.ZwrocZalogowanychResponse klient_wpf.Glowny.GlownySoap.ZwrocZalogowanych(klient_wpf.Glowny.ZwrocZalogowanychRequest request) {
            return base.Channel.ZwrocZalogowanych(request);
        }
        
        public klient_wpf.Glowny.Uzytkownik[] ZwrocZalogowanych() {
            klient_wpf.Glowny.ZwrocZalogowanychRequest inValue = new klient_wpf.Glowny.ZwrocZalogowanychRequest();
            inValue.Body = new klient_wpf.Glowny.ZwrocZalogowanychRequestBody();
            klient_wpf.Glowny.ZwrocZalogowanychResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).ZwrocZalogowanych(inValue);
            return retVal.Body.ZwrocZalogowanychResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.ZwrocZalogowanychResponse> klient_wpf.Glowny.GlownySoap.ZwrocZalogowanychAsync(klient_wpf.Glowny.ZwrocZalogowanychRequest request) {
            return base.Channel.ZwrocZalogowanychAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.ZwrocZalogowanychResponse> ZwrocZalogowanychAsync() {
            klient_wpf.Glowny.ZwrocZalogowanychRequest inValue = new klient_wpf.Glowny.ZwrocZalogowanychRequest();
            inValue.Body = new klient_wpf.Glowny.ZwrocZalogowanychRequestBody();
            return ((klient_wpf.Glowny.GlownySoap)(this)).ZwrocZalogowanychAsync(inValue);
        }
        
        public bool dodajZw() {
            return base.Channel.dodajZw();
        }
        
        public System.Threading.Tasks.Task<bool> dodajZwAsync() {
            return base.Channel.dodajZwAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.ZarejestrujResponse klient_wpf.Glowny.GlownySoap.Zarejestruj(klient_wpf.Glowny.ZarejestrujRequest request) {
            return base.Channel.Zarejestruj(request);
        }
        
        public klient_wpf.Glowny.Komunikat Zarejestruj(string nazwa, string haslo, string email) {
            klient_wpf.Glowny.ZarejestrujRequest inValue = new klient_wpf.Glowny.ZarejestrujRequest();
            inValue.Body = new klient_wpf.Glowny.ZarejestrujRequestBody();
            inValue.Body.nazwa = nazwa;
            inValue.Body.haslo = haslo;
            inValue.Body.email = email;
            klient_wpf.Glowny.ZarejestrujResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).Zarejestruj(inValue);
            return retVal.Body.ZarejestrujResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.ZarejestrujResponse> klient_wpf.Glowny.GlownySoap.ZarejestrujAsync(klient_wpf.Glowny.ZarejestrujRequest request) {
            return base.Channel.ZarejestrujAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.ZarejestrujResponse> ZarejestrujAsync(string nazwa, string haslo, string email) {
            klient_wpf.Glowny.ZarejestrujRequest inValue = new klient_wpf.Glowny.ZarejestrujRequest();
            inValue.Body = new klient_wpf.Glowny.ZarejestrujRequestBody();
            inValue.Body.nazwa = nazwa;
            inValue.Body.haslo = haslo;
            inValue.Body.email = email;
            return ((klient_wpf.Glowny.GlownySoap)(this)).ZarejestrujAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.SprawdzNazweResponse klient_wpf.Glowny.GlownySoap.SprawdzNazwe(klient_wpf.Glowny.SprawdzNazweRequest request) {
            return base.Channel.SprawdzNazwe(request);
        }
        
        public klient_wpf.Glowny.Komunikat SprawdzNazwe(string nazwa) {
            klient_wpf.Glowny.SprawdzNazweRequest inValue = new klient_wpf.Glowny.SprawdzNazweRequest();
            inValue.Body = new klient_wpf.Glowny.SprawdzNazweRequestBody();
            inValue.Body.nazwa = nazwa;
            klient_wpf.Glowny.SprawdzNazweResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).SprawdzNazwe(inValue);
            return retVal.Body.SprawdzNazweResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.SprawdzNazweResponse> klient_wpf.Glowny.GlownySoap.SprawdzNazweAsync(klient_wpf.Glowny.SprawdzNazweRequest request) {
            return base.Channel.SprawdzNazweAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.SprawdzNazweResponse> SprawdzNazweAsync(string nazwa) {
            klient_wpf.Glowny.SprawdzNazweRequest inValue = new klient_wpf.Glowny.SprawdzNazweRequest();
            inValue.Body = new klient_wpf.Glowny.SprawdzNazweRequestBody();
            inValue.Body.nazwa = nazwa;
            return ((klient_wpf.Glowny.GlownySoap)(this)).SprawdzNazweAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.SprawdzEmailResponse klient_wpf.Glowny.GlownySoap.SprawdzEmail(klient_wpf.Glowny.SprawdzEmailRequest request) {
            return base.Channel.SprawdzEmail(request);
        }
        
        public klient_wpf.Glowny.Komunikat SprawdzEmail(string email) {
            klient_wpf.Glowny.SprawdzEmailRequest inValue = new klient_wpf.Glowny.SprawdzEmailRequest();
            inValue.Body = new klient_wpf.Glowny.SprawdzEmailRequestBody();
            inValue.Body.email = email;
            klient_wpf.Glowny.SprawdzEmailResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).SprawdzEmail(inValue);
            return retVal.Body.SprawdzEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.SprawdzEmailResponse> klient_wpf.Glowny.GlownySoap.SprawdzEmailAsync(klient_wpf.Glowny.SprawdzEmailRequest request) {
            return base.Channel.SprawdzEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.SprawdzEmailResponse> SprawdzEmailAsync(string email) {
            klient_wpf.Glowny.SprawdzEmailRequest inValue = new klient_wpf.Glowny.SprawdzEmailRequest();
            inValue.Body = new klient_wpf.Glowny.SprawdzEmailRequestBody();
            inValue.Body.email = email;
            return ((klient_wpf.Glowny.GlownySoap)(this)).SprawdzEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.ZalogujResponse klient_wpf.Glowny.GlownySoap.Zaloguj(klient_wpf.Glowny.ZalogujRequest request) {
            return base.Channel.Zaloguj(request);
        }
        
        public byte[] Zaloguj(string nazwa, string haslo) {
            klient_wpf.Glowny.ZalogujRequest inValue = new klient_wpf.Glowny.ZalogujRequest();
            inValue.Body = new klient_wpf.Glowny.ZalogujRequestBody();
            inValue.Body.nazwa = nazwa;
            inValue.Body.haslo = haslo;
            klient_wpf.Glowny.ZalogujResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).Zaloguj(inValue);
            return retVal.Body.ZalogujResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.ZalogujResponse> klient_wpf.Glowny.GlownySoap.ZalogujAsync(klient_wpf.Glowny.ZalogujRequest request) {
            return base.Channel.ZalogujAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.ZalogujResponse> ZalogujAsync(string nazwa, string haslo) {
            klient_wpf.Glowny.ZalogujRequest inValue = new klient_wpf.Glowny.ZalogujRequest();
            inValue.Body = new klient_wpf.Glowny.ZalogujRequestBody();
            inValue.Body.nazwa = nazwa;
            inValue.Body.haslo = haslo;
            return ((klient_wpf.Glowny.GlownySoap)(this)).ZalogujAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.WylogujResponse klient_wpf.Glowny.GlownySoap.Wyloguj(klient_wpf.Glowny.WylogujRequest request) {
            return base.Channel.Wyloguj(request);
        }
        
        public klient_wpf.Glowny.Komunikat Wyloguj(byte[] token) {
            klient_wpf.Glowny.WylogujRequest inValue = new klient_wpf.Glowny.WylogujRequest();
            inValue.Body = new klient_wpf.Glowny.WylogujRequestBody();
            inValue.Body.token = token;
            klient_wpf.Glowny.WylogujResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).Wyloguj(inValue);
            return retVal.Body.WylogujResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.WylogujResponse> klient_wpf.Glowny.GlownySoap.WylogujAsync(klient_wpf.Glowny.WylogujRequest request) {
            return base.Channel.WylogujAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.WylogujResponse> WylogujAsync(byte[] token) {
            klient_wpf.Glowny.WylogujRequest inValue = new klient_wpf.Glowny.WylogujRequest();
            inValue.Body = new klient_wpf.Glowny.WylogujRequestBody();
            inValue.Body.token = token;
            return ((klient_wpf.Glowny.GlownySoap)(this)).WylogujAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.PobierzSwojeIDResponse klient_wpf.Glowny.GlownySoap.PobierzSwojeID(klient_wpf.Glowny.PobierzSwojeIDRequest request) {
            return base.Channel.PobierzSwojeID(request);
        }
        
        public klient_wpf.Glowny.Komunikat PobierzSwojeID(byte[] token) {
            klient_wpf.Glowny.PobierzSwojeIDRequest inValue = new klient_wpf.Glowny.PobierzSwojeIDRequest();
            inValue.Body = new klient_wpf.Glowny.PobierzSwojeIDRequestBody();
            inValue.Body.token = token;
            klient_wpf.Glowny.PobierzSwojeIDResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).PobierzSwojeID(inValue);
            return retVal.Body.PobierzSwojeIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.PobierzSwojeIDResponse> klient_wpf.Glowny.GlownySoap.PobierzSwojeIDAsync(klient_wpf.Glowny.PobierzSwojeIDRequest request) {
            return base.Channel.PobierzSwojeIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.PobierzSwojeIDResponse> PobierzSwojeIDAsync(byte[] token) {
            klient_wpf.Glowny.PobierzSwojeIDRequest inValue = new klient_wpf.Glowny.PobierzSwojeIDRequest();
            inValue.Body = new klient_wpf.Glowny.PobierzSwojeIDRequestBody();
            inValue.Body.token = token;
            return ((klient_wpf.Glowny.GlownySoap)(this)).PobierzSwojeIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.PobierzUzytkownikowResponse klient_wpf.Glowny.GlownySoap.PobierzUzytkownikow(klient_wpf.Glowny.PobierzUzytkownikowRequest request) {
            return base.Channel.PobierzUzytkownikow(request);
        }
        
        public klient_wpf.Glowny.Uzytkownik[] PobierzUzytkownikow(byte[] token) {
            klient_wpf.Glowny.PobierzUzytkownikowRequest inValue = new klient_wpf.Glowny.PobierzUzytkownikowRequest();
            inValue.Body = new klient_wpf.Glowny.PobierzUzytkownikowRequestBody();
            inValue.Body.token = token;
            klient_wpf.Glowny.PobierzUzytkownikowResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).PobierzUzytkownikow(inValue);
            return retVal.Body.PobierzUzytkownikowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.PobierzUzytkownikowResponse> klient_wpf.Glowny.GlownySoap.PobierzUzytkownikowAsync(klient_wpf.Glowny.PobierzUzytkownikowRequest request) {
            return base.Channel.PobierzUzytkownikowAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.PobierzUzytkownikowResponse> PobierzUzytkownikowAsync(byte[] token) {
            klient_wpf.Glowny.PobierzUzytkownikowRequest inValue = new klient_wpf.Glowny.PobierzUzytkownikowRequest();
            inValue.Body = new klient_wpf.Glowny.PobierzUzytkownikowRequestBody();
            inValue.Body.token = token;
            return ((klient_wpf.Glowny.GlownySoap)(this)).PobierzUzytkownikowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.PobierzWiadomosciResponse klient_wpf.Glowny.GlownySoap.PobierzWiadomosci(klient_wpf.Glowny.PobierzWiadomosciRequest request) {
            return base.Channel.PobierzWiadomosci(request);
        }
        
        public klient_wpf.Glowny.Wiadomosc[] PobierzWiadomosci(byte[] token, int timT, long pokoj) {
            klient_wpf.Glowny.PobierzWiadomosciRequest inValue = new klient_wpf.Glowny.PobierzWiadomosciRequest();
            inValue.Body = new klient_wpf.Glowny.PobierzWiadomosciRequestBody();
            inValue.Body.token = token;
            inValue.Body.timT = timT;
            inValue.Body.pokoj = pokoj;
            klient_wpf.Glowny.PobierzWiadomosciResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).PobierzWiadomosci(inValue);
            return retVal.Body.PobierzWiadomosciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.PobierzWiadomosciResponse> klient_wpf.Glowny.GlownySoap.PobierzWiadomosciAsync(klient_wpf.Glowny.PobierzWiadomosciRequest request) {
            return base.Channel.PobierzWiadomosciAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.PobierzWiadomosciResponse> PobierzWiadomosciAsync(byte[] token, int timT, long pokoj) {
            klient_wpf.Glowny.PobierzWiadomosciRequest inValue = new klient_wpf.Glowny.PobierzWiadomosciRequest();
            inValue.Body = new klient_wpf.Glowny.PobierzWiadomosciRequestBody();
            inValue.Body.token = token;
            inValue.Body.timT = timT;
            inValue.Body.pokoj = pokoj;
            return ((klient_wpf.Glowny.GlownySoap)(this)).PobierzWiadomosciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        klient_wpf.Glowny.WyslijWiadomoscResponse klient_wpf.Glowny.GlownySoap.WyslijWiadomosc(klient_wpf.Glowny.WyslijWiadomoscRequest request) {
            return base.Channel.WyslijWiadomosc(request);
        }
        
        public klient_wpf.Glowny.Komunikat WyslijWiadomosc(byte[] token, klient_wpf.Glowny.Wiadomosc wiadomosc) {
            klient_wpf.Glowny.WyslijWiadomoscRequest inValue = new klient_wpf.Glowny.WyslijWiadomoscRequest();
            inValue.Body = new klient_wpf.Glowny.WyslijWiadomoscRequestBody();
            inValue.Body.token = token;
            inValue.Body.wiadomosc = wiadomosc;
            klient_wpf.Glowny.WyslijWiadomoscResponse retVal = ((klient_wpf.Glowny.GlownySoap)(this)).WyslijWiadomosc(inValue);
            return retVal.Body.WyslijWiadomoscResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<klient_wpf.Glowny.WyslijWiadomoscResponse> klient_wpf.Glowny.GlownySoap.WyslijWiadomoscAsync(klient_wpf.Glowny.WyslijWiadomoscRequest request) {
            return base.Channel.WyslijWiadomoscAsync(request);
        }
        
        public System.Threading.Tasks.Task<klient_wpf.Glowny.WyslijWiadomoscResponse> WyslijWiadomoscAsync(byte[] token, klient_wpf.Glowny.Wiadomosc wiadomosc) {
            klient_wpf.Glowny.WyslijWiadomoscRequest inValue = new klient_wpf.Glowny.WyslijWiadomoscRequest();
            inValue.Body = new klient_wpf.Glowny.WyslijWiadomoscRequestBody();
            inValue.Body.token = token;
            inValue.Body.wiadomosc = wiadomosc;
            return ((klient_wpf.Glowny.GlownySoap)(this)).WyslijWiadomoscAsync(inValue);
        }
    }
}
